version: '3.8'

services:
  app:
    build: .
    ports:
      - "8443:8443"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SSL_KEYSTORE_PASSWORD: ${SSL_KEYSTORE_PASSWORD}
      MINIO_CLIENT_USER: ${MINIO_CLIENT_USER}
      MINIO_CLIENT_PASSWORD: ${MINIO_CLIENT_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    volumes:
      - ./logs:/app/logs
      - ./src/main/resources/script:/docker-entrypoint-initdb.d
    depends_on:
      - db
      - redis
      - minio

  db:
    image: postgres:latest
    ports:
      - "5439:5432"
    environment:
      POSTGRES_DB: gymtracker
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/main/resources/script:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_CLIENT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_CLIENT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - ~/data/minio:/data

volumes:
  pgdata:
  redisdata:
  miniodata:
