INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Базовое упражнение для увеличения массы и силы грудных мышц. Выполняется лёжа на горизонтальной скамье.', 'Жим штанги лежа', 'Грудь', 'https://www.youtube.com/embed/haAmJyTFMKE');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Аналог жима штанги, позволяющий развивать грудные мышцы с большей амплитудой движений.', 'Жим гантелей лежа', 'Грудь', 'https://www.youtube.com/embed/n48eoyd53kk');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Изолирующее упражнение для тренировки средней части грудных мышц. Выполняется лёжа на скамье.', 'Разводка гантелей лежа', 'Грудь', 'https://www.youtube.com/embed/iurQxojfNpk');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Упражнение для акцентированной проработки верхней части грудных мышц. Выполняется на наклонной скамье.', 'Жим на наклонной скамье', 'Грудь', 'https://www.youtube.com/embed/Wqq1D8FHKI');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Упражнение, которое развивает грудные мышцы, а также увеличивает объём грудной клетки.', 'Пуловер с гантелей', 'Грудь', 'https://www.youtube.com/embed/SEfevMz3BZc');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Изолирующее упражнение на тренажёре для грудных мышц, акцентирующее внутреннюю часть груди.', 'Бабочка (Pec Deck)', 'Грудь', 'https://www.youtube.com/embed/2LkDR19nHBc');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Альтернатива жиму штанги, выполняемая в тренажере для большей стабильности и безопасности.', 'Жим в тренажере Смита', 'Грудь', 'https://www.youtube.com/embed/5AiX73QE0ZQ');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Отличное упражнение для тренировки нижней части грудных мышц. Выполняется на брусьях.', 'Отжимания на брусьях', 'Грудь', 'https://www.youtube.com/embed/ORE34_2m62A');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Изолированное упражнение для проработки средней и внутренней части грудных мышц. Выполняется на кроссовере.', 'Сведение в кроссовере', 'Грудь', 'https://www.youtube.com/embed/9fk7dXIjKus');


INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Базовое упражнение для развития широчайших мышц спины и плечевого пояса. Выполняется на перекладине.', 'Подтягивания', 'Спина', 'https://www.youtube.com/embed/K5UVjeNCKmY');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Упражнение для широчайших мышц спины, которое является аналогом подтягиваний для тех, кому они даются с трудом.', 'Тяга верхнего блока', 'Спина', 'https://www.youtube.com/embed/P0JQiVi4y3E');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Силовое упражнение для развития толщины спины, особенно средней и нижней её части.', 'Тяга штанги в наклоне', 'Спина', 'https://www.youtube.com/embed/94CdlnnnwtQ');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Упражнение для тренировки средней части спины и ромбовидных мышц. Выполняется на тренажёре с блоком.', 'Тяга горизонтального блока', 'Спина', 'https://www.youtube.com/embed/jZDy8b0w9QM');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Силовое упражнение для средней части спины и развития мышечной массы.', 'Тяга Т-грифа', 'Спина', 'https://www.youtube.com/embed/eUN7f_hpgDQ');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Одностороннее упражнение, которое помогает развивать симметрию и толщину спины.', 'Тяга гантели в наклоне', 'Спина', 'https://www.youtube.com/embed/Xkq7Z-VfUwY');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Одно из лучших базовых упражнений для развития силы спины, ног и всей задней цепи мышц.', 'Мёртвая тяга', 'Спина', 'https://www.youtube.com/embed/kDDj5mz2XJo');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Упражнение для тренировки трапециевидных мышц, которое выполняется с штангой или гантелями.', 'Шраги со штангой', 'Спина', 'https://www.youtube.com/embed/fLKX1dU');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Упражнение для укрепления поясничного отдела спины. Выполняется на специальной скамье.', 'Гиперэкстензия', 'Спина', 'https://www.youtube.com/embed/ykGsGlXkEVg');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Упражнение помогает прорабатывать мышцы спины, особенно широчайших и проводить эффективные изолирующие упражнения', 'Рычажная тяга', 'Спина', 'https://www.youtube.com/embed/banZUrczIiM');


INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Базовое упражнение для развития силы и объёма дельтовидных мышц и трицепсов. Выполняется стоя со штангой.', 'Армейский жим стоя', 'Плечи', 'https://www.youtube.com/embed/YgM_uMeNZpI');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Упражнение для тренировки передней и средней части дельтовидных мышц. Выполняется сидя с гантелями.', 'Жим гантелей сидя', 'Плечи', 'https://www.youtube.com/embed/MT0Z1J6TPKE');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Изолированное упражнение для развития средней части дельтовидных мышц.', 'Махи гантелями в стороны', 'Плечи', 'https://www.youtube.com/embed/rLudVBlN0-A');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Упражнение для тренировки передней части дельтовидных мышц. Выполняется с гантелями.', 'Махи гантелями перед собой', 'Плечи', 'https://www.youtube.com/embed/X83tkn4qiJA');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Изолированное упражнение для задней части дельтовидных мышц. Выполняется в наклоне с гантелями.', 'Обратные махи в наклоне', 'Плечи', 'https://www.youtube.com/embed/SbMVhF7SQwU');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Вариация жима, выполняемая сидя или стоя, акцентирующая нагрузку на переднюю и среднюю часть плеч.', 'Жим штанги из-за головы', 'Плечи', 'https://www.youtube.com/embed/WvqiH_icXBw');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Изолированное упражнение для задних дельт. Выполняется на тренажёре, аналогично разведению рук с гантелями.', 'Разводка в тренажёре (обратная бабочка)', 'Плечи', 'https://www.youtube.com/embed/zwoUtsAfB2Q');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Многофункциональное упражнение, задействующее плечи и трапеции. Выполняется стоя с узким хватом.', 'Тяга штанги к подбородку', 'Плечи', 'https://www.youtube.com/embed/HD1uRgLWSXY');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Упражнение, акцентирующее нагрузку на переднюю часть дельтовидных мышц. Выполняется стоя с гантелями.', 'Подъем гантелей перед собой', 'Плечи', 'https://www.youtube.com/embed/RpfsK22xrG0');


INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Базовое упражнение для увеличения силы и объема бицепсов. Выполняется стоя со штангой.', 'Подъем штанги на бицепс стоя', 'Бицепс', 'https://www.youtube.com/embed/APGw5Xi8xfQ');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Упражнение, позволяющее акцентированно прорабатывать каждую руку. Выполняется с гантелями сидя.', 'Подъем гантелей на бицепс сидя', 'Бицепс', 'https://www.youtube.com/embed/P957YHBOs6Q');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Вариация подъема гантелей, при которой кисти находятся в положении "молотка". Прорабатывает бицепсы и плечевые мышцы.', 'Молотковый подъем гантелей', 'Бицепс', 'https://www.youtube.com/embed/xkA900B4yt4');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Изолирующее упражнение, которое выполняется одной рукой для максимальной концентрации на бицепсе.', 'Концентрированный подъем на бицепс', 'Бицепс', 'https://www.youtube.com/embed/quKVcoTV8T0');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Вариация упражнения с использованием прямой или изогнутой штанги для изоляции бицепсов.', 'Подъем штанги на скамье Скотта', 'Бицепс', 'https://www.youtube.com/embed/yeUujQ-kERg');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Изолирующее упражнение с использованием кроссовера для постоянного напряжения бицепса на всём диапазоне движения.', 'Подъем на бицепс в кроссовере', 'Бицепс', 'https://www.youtube.com/embed/3DAvkrINsss');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Упражнение, которое развивает как бицепсы, так и мышцы спины, выполняется с обратным хватом на турнике.', 'Подтягивания обратным хватом', 'Бицепс', 'https://www.youtube.com/embed/qY2k9p33J7U');


INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Базовое упражнение, выполняемое на горизонтальной скамье для развития силы и массы трицепсов.', 'Жим штанги узким хватом', 'Трицепс', 'https://www.youtube.com/embed/kbf_MdonwSs');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Многофункциональное упражнение для трицепсов и грудных мышц. Выполняется на брусьях с акцентом на руки.', 'Отжимания на брусьях', 'Трицепс', 'https://www.youtube.com/embed/rCR4RuT-2KQ');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Изолированное физическое упражнение для тренировки трицепс', 'Французский жим', 'Трицепс', 'https://www.youtube.com/embed/SS5OO8ekqgI');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Упражнение для развития длинной головки трицепса. Выполняется одной рукой или двумя руками одновременно.', 'Разгибание гантели из-за головы', 'Трицепс', 'https://www.youtube.com/embed/OPzBaL7AAeQ');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Изолированное упражнение, которое развивает трицепсы, выполняется в наклоне с гантелями.', 'Разгибание рук с гантелями в наклоне', 'Трицепс', 'https://www.youtube.com/embed/1ZRjTMsukEs');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Вариация разгибаний на блоке с использованием каната, позволяющая дополнительно проработать трицепсы.', 'Разгибание рук с канатом на блоке', 'Трицепс', 'https://www.youtube.com/embed/icvO137ycc8');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Изолированное упражнение для развития трицепсов. Выполняется на верхнем блоке с рукояткой.', 'Разгибание рук на блоке', 'Трицепс', 'https://www.youtube.com/embed/DG_qts6PodE');

INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Базовое упражнение для проработки прямых мышц живота. Выполняется лёжа на спине с согнутыми коленями.', 'Скручивания', 'Пресс', 'https://www.youtube.com/embed/H8xSHCAjM-I');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Статическое упражнение для укрепления мышц кора, включая пресс, спину и плечи. Выполняется в положении упора на локтях.', 'Планка', 'Пресс', 'https://www.youtube.com/embed/0JtBS11DGDk');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Эффективное упражнение для нижней части пресса. Выполняется на турнике с поднятием ног к животу.', 'Подъем ног в висе', 'Пресс', 'https://www.youtube.com/embed/CNj1xF2ona0');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Упражнение для проработки косых мышц живота. Выполняется сидя с поворотами корпуса.', 'Русские скручивания', 'Пресс', 'https://www.youtube.com/embed/nXLh8xsbvWM');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Упражнение, направленное на нижнюю часть пресса. Выполняется лёжа на спине с подтягиванием коленей к груди.', 'Обратные скручивания', 'Пресс', 'https://www.youtube.com/embed/g3HX9ixGKe4');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Упражнение для развития верхней части пресса, выполняемое на наклонной скамье.', 'Скручивания на скамье', 'Пресс', 'https://www.youtube.com/embed/4hR_-_e3-I4');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Упражнение для проработки всех частей пресса, выполняемое в положении лёжа с имитацией езды на велосипеде.', 'Велосипед', 'Пресс', 'https://www.youtube.com/embed/S_g3oBJKpRM');


INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Базовое упражнение для тренировки мышц ног, включая квадрицепсы, ягодицы и заднюю поверхность бедра.', 'Приседания со штангой', 'Ноги', 'https://www.youtube.com/embed/Om8D3BkKPC4');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Упражнение для проработки всех мышц ног с акцентом на квадрицепсы и ягодицы. Выполняется в тренажере.', 'Жим ногами в тренажере', 'Ноги', 'https://www.youtube.com/embed/jyphzYKrptw');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Комплексное упражнение для тренировки задней поверхности ног и спины, выполняемое с отягощением.', 'Становая тяга', 'Ноги', 'https://www.youtube.com/embed/KddlE57Yjt0');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Изолирующее упражнение для квадрицепсов, выполняемое в тренажере с использованием отягощения.', 'Разгибание ног в тренажере', 'Ноги', 'https://www.youtube.com/embed/eT4thXaPR8w');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Изолирующее упражнение для задней поверхности бедра, выполняемое в тренажере с отягощением.', 'Сгибание ног в тренажере', 'Ноги', 'https://www.youtube.com/embed/4xEzsITA4Lc');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Упражнение для тренировки квадрицепсов, ягодиц и задней поверхности бедра.', 'Болгарские выпады', 'Ноги', 'https://www.youtube.com/embed/IiycRg2N0cY');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Упражнение для тренировки икроножных мышц, выполняемое в тренажере или стоя.', 'Подъем на носки', 'Ноги', 'https://www.youtube.com/embed/XitPbkHneD4');
INSERT INTO exercise ( description, name, muscle_group, media_url) VALUES ( 'Вариация приседаний, выполняемая в тренажере для жима ногами, акцентирующая нагрузку на квадрицепсы.', 'Гакк-приседания', 'Ноги', 'https://www.youtube.com/embed/MBOkwJT56Gw');


